extends Node

signal next_type()
signal send_tea()

enum INGREDIENTS {
	NONE,
	TEA1,
	TEA2,
	TEA3,
	TEA4,
	TEA5,
	TEA6,
	SWEETENER1,
	SWEETENER2,
	SWEETENER3,
	SWEETENER4,
	SWEETENER5,
	SWEETENER6,
	EXTRA1,
	EXTRA2,
	EXTRA3,
	EXTRA4,
	EXTRA5,
	EXTRA6
}

enum TYPES {
	TEA,
	SWEETENER,
	EXTRA
}

var current_ingredient : INGREDIENTS = INGREDIENTS.NONE
var current_type : TYPES = TYPES.TEA
var current_customer : Node2D = null
var money : int = 1000
var unlocked_ingredients : Array[INGREDIENTS] = [
	INGREDIENTS.TEA1,
	INGREDIENTS.TEA2,
	INGREDIENTS.TEA3,
	INGREDIENTS.SWEETENER1,
	INGREDIENTS.SWEETENER2,
	INGREDIENTS.SWEETENER3,
	INGREDIENTS.EXTRA1,
	INGREDIENTS.EXTRA2,
	INGREDIENTS.EXTRA3
]
